apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service
  namespace: ai
  labels:
    app: aetherial
    component: llm-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aetherial
      component: llm-service
  template:
    metadata:
      labels:
        app: aetherial
        component: llm-service
    spec:
      containers:
      - name: llm-service
        image: ${REGISTRY}/${IMAGE_REPO}/llm-service:${VERSION}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: MODEL_NAME
          value: "aetherial/llm-base"
        - name: DEVICE
          value: "cuda"
        resources:
          limits:
            nvidia.com/gpu: 1
            cpu: 4000m
            memory: 16Gi
          requests:
            cpu: 2000m
            memory: 8Gi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: llm-service
  namespace: ai
  labels:
    app: aetherial
    component: llm-service
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: aetherial
    component: llm-service
  type: ClusterIP
